apiVersion: v1
kind: Service
metadata:
  name: tictactoe-game-api-service
spec:
  selector:
    app: tictactoe-game-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8282
      nodePort: 30001
  type: LoadBalancer